language: python

services:
  - docker

before_install:
  - docker-compose build

install:
  - pip install -r orders-app/requirements/requirements.txt

script:
  - coverage run -m pytest --source app
  - docker-compose run orders_app pytest

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main
