version: "3.7"
services:
  orders_app:
    build: './orders-app'
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - redis

  comms_worker:
    build: './comms-worker'
    user: nobody
    environment:
      - AT_API_KEY=${AT_API_KEY}
      - AT_USERNAME=${AT_USERNAME}
    depends_on:
      - redis
      - orders_app

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
