name: Build, test and publish images
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the services
        run: |
          export AT_API_KEY=${{secrets.AT_API_KEY}}
          export AT_USERNAME=${{secrets.AT_USERNAME}}
          echo $AT_USERNAME
          export SECRET_KEY=${{secrets.SECRET_KEY}}
          export POSTGRES_DB=${{secrets.POSTGRES_DB}}
          export POSTGRES_USER=${{secrets.POSTGRES_USER}}
          export POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}

          docker-compose build

      - name: Run tests
        run: docker-compose run savannah-orders_orders_app pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Publish image
        run: |
          docker push dansonio/savannah-orders_orders_app
          docker push dansonio/savannah-orders_comms_worker
