name: Build, test and publish images
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the services
        run: docker-compose build

      - name: Run tests
        env:
          AT_API_KEY : ${{secrets.AT_API_KEY}}
          AT_USERNAME : ${{secrets.AT_USERNAME}}
          SECRET_KEY : ${{secrets.SECRET_KEY}}
          POSTGRES_DB : ${{secrets.POSTGRES_DB}}
          POSTGRES_USER : ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD : ${{secrets.POSTGRES_PASSWORD}}

        run: docker-compose run orders_app pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish image
        run: |
          docker push dansonio/savannah-orders_orders_app
          docker push dansonio/savannah-orders_comms_worker
